CREATE PROC uspProc2
AS
SELECT Number_of_Copies, BranchName 
FROM BOOK_COPIES
 INNER JOIN BOOKS ON BOOK_COPIES.BookID=BOOKS.BookID
 INNER JOIN LIBRARY_BRANCH ON BOOK_COPIES.BranchID=LIBRARY_BRANCH.BranchID
WHERE Title = 'The Lost Tribe';

EXEC uspProc2

