USE db_LIBRARY
GO
CREATE PROC uspProc7
AS
SELECT BOOKS.Title, BOOK_COPIES.Number_Of_Copies,LIBRARY_BRANCH.BranchName
FROM BOOKS
	INNER JOIN BOOK_COPIES ON BOOK_COPIES.BookID = BOOKS.BookID
	INNER JOIN LIBRARY_BRANCH ON LIBRARY_BRANCH.BranchID = BOOK_COPIES.BranchID
	INNER JOIN BOOK_AUTHORS ON BOOK_AUTHORS.BookID = BOOKS.BookID	
WHERE AuthorName = 'Stephen King' AND BranchName = 'CENTRAL'

EXEC uspProc7
