USE db_LIBRARY
GO
CREATE PROC uspProc6
AS
SELECT BORROWER.Name, BORROWER.Address, COUNT(BOOK_LOANS.CardNO)
FROM BORROWER
   INNER JOIN BOOK_LOANS ON BOOK_LOANS.CardNO = BORROWER.CardNo
GROUP BY BORROWER.Name, BORROWER.Address
HAVING COUNT(BOOK_LOANS.CardNO) > 5;

EXEC uspProc6

