USE db_LIBRARY
GO
CREATE PROC uspPROC4
AS
SELECT BOOKS.Title, BORROWER.Name, BORROWER.Address
FROM BOOKS
	INNER JOIN BOOK_LOANS ON BOOK_LOANS.BookID = BOOKS.BookID
	INNER JOIN BORROWER ON BORROWER.CardNo = BOOK_LOANS.CardNO
	INNER JOIN LIBRARY_BRANCH ON LIBRARY_BRANCH.BranchID = BOOK_LOANS.BranchID
WHERE BranchName = 'SHARPSTOWN' and DateDue='20200121';
	
EXEC uspPROC4
